// React Native AISummaryCard Component
// Displays AI-generated review summary with beautiful design

import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Spacing, FontSize, BorderRadius, FontWeight, Shadow } from '../constants/theme';
import { useTheme } from '../context/ThemeContext';

interface AISummaryCardProps {
  summary: string;
}

export const AISummaryCard: React.FC<AISummaryCardProps> = ({ summary }) => {
  const { colors } = useTheme();

  // Debug log
  console.log('🎨 AISummaryCard rendering with summary:', summary?.substring(0, 50));

  if (!summary || summary.trim().length === 0) {
    console.warn('⚠️ AISummaryCard: No summary provided');
    return null;
  }

  return (
    <View style={[styles.container, { backgroundColor: colors.card }]}>
      {/* Header with AI badge */}
      <View style={styles.header}>
        <LinearGradient
          colors={['#8B5CF6', '#6366F1']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.aiBadge}
        >
          <Ionicons name="sparkles" size={16} color="#fff" />
          <Text style={styles.aiBadgeText}>AI Summary</Text>
        </LinearGradient>
      </View>

      {/* Summary text */}
      <Text style={[styles.summaryText, { color: colors.foreground }]}>
        {summary}
      </Text>

      {/* Footer note */}
      <View style={[styles.footer, { backgroundColor: colors.secondary }]}>
        <Ionicons name="information-circle-outline" size={14} color={colors.mutedForeground} />
        <Text style={[styles.footerText, { color: colors.mutedForeground }]}>
          Generated by AI · Based on customer reviews
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    ...Shadow.soft,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },

  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
  },

  aiBadgeText: {
    color: '#fff',
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  summaryText: {
    fontSize: FontSize.base,
    lineHeight: FontSize.base * 1.6,
    marginBottom: Spacing.md,
  },

  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
  },

  footerText: {
    fontSize: FontSize.xs,
    fontStyle: 'italic',
  },
});
